addons:
  apt:
    packages:
    - doxygen
    - graphviz
    - autoconf
    - automake

language: c

script: ./autogen.sh && make && make docs

install: true

sudo: false

notifications:
  irc: "chat.freenode.net#code-hell"

